print("basic comparison operators:")
print(f"9 > 3: {9 > 3}")
print(f"9 < 3: {9 < 3}")
print(f"9 >= 9: {9 >= 9}")
print(f"9 <= 9: {9 <= 9}")
print(f"9 == 9: {9 == 9}")
print(f"9 == \"9\": {9 == "9"}")
print(f"9 != 9: {9 != 9}")
print(f"\"bob\" > \"andy\": {"bob" > "andy"}")
print(f"\"andy\" > \"bob\": {"andy" > "bob"}")
print(f"\"Bob\" >= \"bob\": {"Bob" >= "bob"} ")
print(f"\"bob\" == \"bob\": {"bob" == "bob"}")
print(ord("B"))
print(ord("b"))
